export const COMPETITONS = [
    {
        id: 0,
        compId: 'COMP0000',
        incharge: 'TEACH000',
        compType: "Introduction Ramp Walk Round",
        startDate: " Wed Aug 2th 2023 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Wed Aug 2th 2023 13:00:00 GMT +0530 (India Standard Time)",
        name: "Introduction and Ramp Walk Round",
        coverImage: "/assets/images/event0.jpg",
        description: "Ramp walk round of freshers",
        status: "open"
    },
    {
        id: 1,
        compId: 'COMP0001',
        incharge: 'TEACH000',
        compType: "Introduction Ramp Walk Round",
        startDate: " Wed Aug 2 2023 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Wed Aug 2 2023 13:00:00 GMT +0530 (India Standard Time)",
        name: "Introduction Ramp Walk Round",
        coverImage: "/assets/images/event0.jpg",
        description: "Ramp walk round of freshers",
        status: "open"
    },
    {
        id: 2,
        compId: 'COMP0002',
        incharge: 'TEACH000',
        compType: "Question Round",
        startDate: " Wed Aug 2 2023 13:15:00 GMT +0530(India Standard Time)",
        endDate: "Wed Aug 2 2023 14:30:00 GMT +0530 (India Standard Time)",
        name: "Question Round",
        coverImage: "/assets/images/event0.jpg",
        description: "Talent Question/Answers Round",
        status: "open"
    },
    {
        id: 3,
        compId: 'COMP0003',
        incharge: 'TEACH000',
        compType: "Talent Round",
        startDate: " Wed Aug 2 2023 14:45:00 GMT +0530(India Standard Time)",
        endDate: "Wed Aug 2 2023 15:45:00 GMT +0530 (India Standard Time)",
        name: "Talent Round",
        coverImage: "/assets/images/event0.jpg",
        description: "Talent Question/Answers Round",
        status: "open"
    },
    {
        id: 4,
        compId: 'COMP0004',
        incharge: 'TEACH000',
        compType: "Prize Distribution",
        startDate: " Wed Aug 2 2023 16:00:00 GMT +0530(India Standard Time)",
        endDate: "Wed Aug 2 2023 16:45:00 GMT +0530 (India Standard Time)",
        name: "Prize Distribution",
        coverImage: "/assets/images/event0.jpg",
        description: "Distributing Prizes to the winners",
        status: "open"
    },
    {
        id: 5,
        compId: 'COMP0005',
        incharge: 'TEACH002',
        compType: "Bhangra competition",
        startDate: " Wed Feb 22 2023 10:00:00 GMT +0530(India Standard Time)",
        endDate: "Wed Feb 22 2023 12:30:00 GMT +0530 (India Standard Time)",
        name: "Bhangra competition",
        coverImage: "/assets/images/event0.jpg",
        description: "Interzonal Bhangra competiton",
        status: "open"
    },
    {
        id: 6,
        compId: 'COMP0006',
        incharge: 'TEACH002',
        compType: "Western Dance competition",
        startDate: " Wed Feb 22 2023 13:00:00 GMT +0530(India Standard Time)",
        endDate: "Wed Feb 22 2023 15:30:00 GMT +0530 (India Standard Time)",
        name: "Western Dance competition",
        coverImage: "/assets/images/event0.jpg",
        description: "Interzonal Western Dance competiton",
        status: "open",
    },
    {
        id: 7,
        compId: 'COMP0007',
        incharge: 'TEACH002',
        compType: "Singing competition",
        startDate: "Thu Feb 23 2023 10:00:00 GMT +0530(India Standard Time)",
        endDate: "Thu Feb 23 2023 12:30:00 GMT +0530 (India Standard Time)",
        name: "Singing COMPetition",
        coverImage: "/assets/images/event0.jpg",
        description:"Interzonal Singing competiton",
        status: "open"
    },    
    {
        id: 8,
        compId: 'COMP0008',
        incharge: 'TEACH002',
        compType: "Theatre competition",
        startDate: " Thu Feb 23 2023 12:45:00 GMT +0530(India Standard Time)",
        endDate: "Thu Feb 23 2023 17:00:00 GMT +0530 (India Standard Time)",
        name: "Mime Act",
        coverImage: "/assets/images/event0.jpg",
        description:"Interzonal Theatre competiton",
        status: "open"
    },
    {
        id: 9,
        compId: 'COMP0009',
        incharge: 'TEACH002',
        compType: "Art competition",
        startDate: " Thu Feb 24 2023 10:00:00 GMT +0530(India Standard Time)",
        endDate: "Thu Feb 24 2023 14:00:00 GMT +0530 (India Standard Time)",
        name: "Art competition",
        coverImage: "/assets/images/event0.jpg",
        description: "Interzonal Art competition",
        status: "open"
    },
    {
        id: 10,
        compId: 'COMP0010',
        incharge: 'TEACH002',
        compType: "Prize Distribution",
        startDate: " Fri Feb 2 2023 12:15:00 GMT +0530(India Standard Time)",
        endDate: "Fri Feb 2 2023 17:00:00 GMT +0530 (India Standard Time)",
        name: "Prize Distribution",
        coverImage: "/assets/images/event0.jpg",
        description: "Distributing Prizes to the Interzonal winners",
        status: "open"
    },
    {
        id: 11,
        compId: 'COMP0011',
        incharge: 'TEACH004',
        compType: "100m Dash",
        startDate: " Fri Oct 13 2023 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Fri Oct 13 2023 12:00:00 GMT +0530 (India Standard Time)",
        name: "100m Dash",
        coverImage: "/assets/images/event0.jpg",
        description: "100m Dash",
        status: "open"
    },
    {
        id: 12,
        compId: 'COMP0012',
        incharge: 'TEACH004',
        compType: "400m Relay Race",
        startDate: " Fri Oct 13 2023 12:00:00 GMT +0530(India Standard Time)",
        endDate: "Fri Oct 13 2023 13:00:00 GMT +0530 (India Standard Time)",
        name: "400m Relay Race",
        coverImage: "/assets/images/event0.jpg",
        description: "400m Relay Race",
        status: "open"
    },
    {
        id: 13,
        compId: 'COMP0013',
        incharge: 'TEACH003',
        compType: "Sports",
        startDate: " Fri Oct 13 2022 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Fri Oct 13 2022 17:00:00 GMT +0530 (India Standard Time)",
        name: "Quater Finals",
        coverImage: "/assets/images/event0.jpg",
        description: "Quater Finals of football competion",
        status: "closed"
    },
    {
        id: 14,
        compId: 'COMP0014',
        incharge: 'TEACH003',
        compType: "Sports",
        startDate: " Sat Oct 14 2022 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Sat Oct 14 2022 17:00:00 GMT +0530 (India Standard Time)",
        name: "Semi Finals",
        coverImage: "/assets/images/event0.jpg",
        description: "Semi Finals of football competion",
        status: "closed"
    },
    {
        id: 15,
        compId: 'COMP0015',
        incharge: 'TEACH003',
        compType: "Sports",
        startDate: " Mon Oct 16 2022 13:00:00 GMT +0530(India Standard Time)",
        endDate: "Mon Oct 16 2022 17:00:00 GMT +0530 (India Standard Time)",
        name: "Finals",
        coverImage: "/assets/images/event0.jpg",
        description: "Finals of football COMPetion",
        status: "closed"
    },
    {
        id: 16,
        compId: 'COMP0016',
        incharge: 'TEACH003',
        compType: "Sports",
        startDate: " Mon Oct 16 2022 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Mon Oct 16 2022 17:00:00 GMT +0530 (India Standard Time)",
        name: "Quater Finals",
        coverImage: "/assets/images/event0.jpg",
        description: "Quater Finals of Basketball competion",
        status: "closed"
    },
    {
        id: 17,
        compId: 'COMP0017',
        incharge: 'TEACH003',
        compType: "Sports",
        startDate: " Tue Oct 17 2022 11:00:00 GMT +0530(India Standard Time)",
        endDate: "Tue Oct 17 2022 17:00:00 GMT +0530 (India Standard Time)",
        name: "Semi Finals",
        coverImage: "/assets/images/event0.jpg",
        description: "Semi Finals of Basketball competion",
        status: "closed"
    },
    {
        id: 18,
        compId: 'COMP0018',
        incharge: 'TEACH003',
        compType: "Sports",
        startDate: " Wed Oct 18 2022 13:00:00 GMT +0530(India Standard Time)",
        endDate: "Wed Oct 18 2022 17:00:00 GMT +0530 (India Standard Time)",
        name: "Finals",
        coverImage: "/assets/images/event0.jpg",
        description: "Finals of Basketball COMPetion",
        status: "closed"
    }
];