export const USERS = [
    {
        id: 0,
        userId: 'ADMIN000',
        name: 'Admin Admin',
        userType: 'admin',
        phone: "0000000000",
        email: "admin000@xyz.edu",
        username: "admin000",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "NA"
    },
    {
        id: 1,
        userId: 'ADMIN001',
        name: 'Admin Admin',
        userType: 'admin',
        phone: "0000000000",
        email: "admin001@xyz.edu",
        username: "admin001",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "NA"
    },
    {
        id: 2,
        userId: 'ADMIN002',
        name: 'Admin Admin',
        userType: 'admin',
        phone: "0000000000",
        email: "admin001@xyz.edu",
        username: "admin001",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "NA"
    },
    {
        id: 3,
        userId: 'ADMIN003',
        name: 'Admin Admin',
        userType: 'admin',
        phone: "0000000000",
        email: "admin003@xyz.edu",
        username: "admin003",
        password: "0003",
        gender: "male",
        rollno: "NA",
        department: "NA"
    },
    {
        id: 4,
        userId: 'ADMIN004',
        name: 'Admin Admin',
        userType: 'admin',
        phone: "0000000000",
        email: "admin004@xyz.edu",
        username: "admin004",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "NA"
    },
    {
        id: 20,
        userId: 'TEACH000',
        name: 'Reeta Bharadwaj',
        userType: 'teacher',
        phone: "9876543210",
        email: "teacher000@xyz.edu",
        username: "reeta_bharadwaj000",
        password: "0000",
        gender: "female",
        rollno: "NA",
        department: "IT"
    },
    {
        id: 21,
        userId: 'TEACH001',
        name: 'Gagan Bharadwaj',
        userType: 'teacher',
        phone: "9876543210",
        email: "teacher001@xyz.edu",
        username: "gagan_bharadwaj000",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "IT"
    },
    {
        id: 22,
        userId: 'TEACH002',
        name: 'Teach two',
        userType: 'teacher',
        phone: "9876543210",
        email: "teach_two@xyz.edu",
        username: "teach_two",
        password: "0000",
        gender: "female",
        rollno: "NA",
        department: "CSE"
    },
    {
        id: 23,
        userId: 'TEACH003',
        name: 'Teach Three',
        userType: 'teacher',
        phone: "9876543210",
        email: "teach_three@xyz.edu",
        username: "teach_three",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "CSE"
    },
    {
        id: 24,
        userId: 'TEACH004',
        name: 'Teach Four',
        userType: 'teacher',
        phone: "9876543210",
        email: "teacher004@xyz.edu",
        username: "teach_4",
        password: "0000",
        gender: "male",
        rollno: "NA",
        department: "ECE"
    },
    
    {
        id: 50,
        userId: 'STU40319',
        name: 'Aditya Jain',
        userType: 'student',
        phone: "9876543210",
        email: "abc@xyz.edu",
        username: "aditya_jain1511",
        password: "0000",
        gender: "male",
        rollno: "1903814",
        department: "IT"
    },
    {
        id: 51,
        userId: 'STU42019',
        name: 'HarnoorDeep Singh',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "harnoor_singh0104",
        password: "0000",
        gender: "male",
        rollno: "1903832",
        department: "IT"
    },
    {
        id: 52,
        userId: 'STU42119',
        name: 'Harman Preet',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "harman0104",
        password: "0000",
        gender: "female",
        rollno: "1903833",
        department: "IT"
    },
    {
        id: 53,
        userId: 'STU40719',
        name: 'Deepesh Singh',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "deep_singh0104",
        password: "0000",
        gender: "male",
        rollno: "1903818",
        department: "IT"
    },
    {
        id: 54,
        userId: 'STU40119',
        name: 'Aastha Narula',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "aasthanarula",
        password: "0000",
        gender: "female",
        rollno: "1903812",
        department: "IT"
    },
    {
        id: 55,
        userId: 'STU40219',
        name: 'Aadit kumar',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "aadit",
        password: "0000",
        gender: "male",
        rollno: "1903813",
        department: "IT"
    },
    {
        id: 56,
        userId: 'STU40419',
        name: 'Akil Mehta',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "akilmehta",
        password: "0000",
        gender: "male",
        rollno: "1903815",
        department: "IT"
    },
    {
        id: 57,
        userId: 'STU30119',
        name: 'Harnoor Gandhi',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "harnoor_gandhi0104",
        password: "0000",
        gender: "male",
        rollno: "1903701",
        department: "CSE"
    },
    {
        id: 58,
        userId: 'STU30219',
        name: 'segal chadha',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "segalc",
        password: "0000",
        gender: "male",
        rollno: "1903702",
        department: "CSE"
    },
    {
        id: 59,
        userId: 'STU30319',
        name: 'anshika kohli',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "anshu_k",
        password: "0000",
        gender: "female",
        rollno: "1903820",
        department: "CSE"
    },
    {
        id: 60,
        userId: 'STU30419',
        name: 'anamika chauhan',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "anna_ch",
        password: "0000",
        gender: "female",
        rollno: "1903834",
        department: "CSE"
    },
    {
        id: 61,
        userId: 'STU30519',
        name: 'Shruti Garg',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "shruti_garg1311",
        password: "0000",
        gender: "female",
        rollno: "1903836",
        department: "CSE"
    },
    {
        id: 62,
        userId: 'TEST0619',
        name: 'test Test',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "test001",
        password: "0000",
        gender: "male",
        rollno: "1903837",
        department: "CSE"
    },
    {
        id: 63,
        userId: 'Test0719',
        name: 'test test02',
        userType: 'student',
        phone: "9876543210",
        email: "def@xyz.edu",
        username: "test002",
        password: "0000",
        gender: "female",
        rollno: "1903838",
        department: "ECE"
    }
  ];